# Generated by Django 2.2 on 2019-04-24 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzashopapp', '0003_auto_20190415_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='logo',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='pizza',
            name='pizzashop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzashopapp.PizzaShop'),
        ),
    ]
