# Generated by Django 2.2 on 2019-05-07 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzashopapp', '0004_auto_20190424_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='pizzashop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzashopapp.PizzaShop'),
        ),
    ]
